### ISSUE TITLE
Error creating All:All matrix

### ISSUE THREAD

**Issue by Phlya** [paulsengroup/hictk#178]
Hi, I am trying out hictk to convert .mcool to .hic, and I am encountering an issue. After writing all by-chromosome pixels, it tries to create the All:All matrix and fails like this:

```
>hictk convert --threads 8 --tmpdir results/coolers_library_group         results/coolers_library_group/all.sacCer3.mapq_30.1000.mcool results/coolers_library_group/all.sacCer3.mapq_30.1000.hic

...
2024-05-22 13:55:03.595] [info]: writing pixels for All:All matrix...
FAILURE! hictk convert encountered the following error: an error occurred while writing file "results/coolers_library_group/all.sacCer3.mapq_30.1000.hic": an error occurred while writing the 
All:All matrix to file "results/coolers_library_group/all.sacCer3.mapq_30.1000.hic": position is greater than chromosome size: 4140417920 >= 1531933
```
This is a tiny .mcool with some yeast data that we use for testing in distiller, the file is attached (changed the extension to txt so github doesn't complain)
[all.sacCer3.mapq_30.1000.txt](https://github.com/paulsengroup/hictk/files/15402918/all.sacCer3.mapq_30.1000.txt)

Am I doing something wrong here?

**Comment by robomics** [comment]
Thanks again for reporting this issue.

The problem turned out to be having bin tables where all chromosomes have exactly one bin.
The code used in hictk to estimate the cache size when opening .hic files had the incorrect assumption that the longest chromosome in a genome has at least two bins.
Violating this assumption led to an integer overflow which resulted in the `position is greater than chromosome size` error.

**Comment by Phlya** [comment]
Thank you for looking into it so quickly!
